name: TableTies
description: "A social dining app to connect like-minded individuals"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  dio: ^4.0.6
  dio_logger: ^4.0.8+8
  supabase_flutter: ^2.6.0
  go_router: ^14.2.3
  flutter_bloc: ^8.1.2
  image_picker: ^1.1.2
  flutter_svg: ^2.0.5
  introduction_screen: ^3.1.8
  http: ^1.2.2
  equatable: ^2.0.5
  flutter_dotenv: ^5.0.2
  logger: ^2.3.0
  shared_preferences: ^2.2.3
  intl: ^0.18.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
